<?php

namespace TotalCMS\Utils\Faker;

class FakerExamples
{
	public const FAKER_EXAMPLES = [
		'word',
		'words(3, false)',
		'sentence(6, true)',
		'sentences(3, false)',
		'paragraph(3, true)',
		'paragraphs(3, false)',
		'text(200)',
		'slug',
		'uuid',
		'boolean',
		'hexColor',
		'realText(200, 2)',
		'realTextBetween(160, 200, 2)',
		'imageUrl(640, 480)',
		'image(640, 480)',
		'imageBlur(640, 480)',
		'imageBW(640, 480)',
		'imageBWBlur(640, 480, 10)',
		'imageText(640, 480, \'f8f8f8\', 200)',
		'imageShapes(640, 480, \'f8f8f8\')',
		'tags(1, 5)',
		'title(\'male\')',
		'titleMale',
		'titleFemale',
		'suffix',
		'name(\'male\')',
		'firstName(\'female\')',
		'firstNameMale',
		'firstNameFemale',
		'lastName',
		'iso8601',
		'date',
		'time',
		'dateTimeBetween(\'-27 week\', \'now\')',
		'cityPrefix',
		'secondaryAddress',
		'state',
		'stateAbbr',
		'citySuffix',
		'streetSuffix',
		'buildingNumber',
		'city',
		'streetName',
		'streetAddress',
		'postcode',
		'address',
		'country',
		'countryCode',
		'emoji',
		'url',
		'latitude(-90, 90)',
		'longitude(-180, 180)',
		'phoneNumber',
		'phoneNumberWithExtension',
		'tollFreePhoneNumber',
		'e164PhoneNumber',
		'catchPhrase',
		'bs',
		'company',
		'companySuffix',
		'jobTitle',
	];
}
