<?php

declare(strict_types=1);

namespace TotalCMS\Domain\Builder\Service;

use TotalCMS\Support\OperationResult;
use TotalCMS\Support\PathResolver;

/**
 * Installs a Vite-based frontend asset pipeline scaffold into a project's
 * `frontend/` directory. The scaffold ships in `resources/builder/frontend/`
 * and is the same for every starter — there's nothing starter-specific
 * about the build pipeline.
 *
 * Idempotent: existing files are skipped unless `$force` is set, so users
 * can safely re-run the installer to pull missing files without losing
 * customizations.
 */
readonly class BuilderFrontendInstaller
{
	public function install(bool $force = false): OperationResult
	{
		$source = $this->scaffoldDir();
		if (!is_dir($source)) {
			return OperationResult::failure("Frontend scaffold missing: {$source}");
		}

		$target = $this->targetDir();
		if (!is_dir($target) && !mkdir($target, 0755, true) && !is_dir($target)) {
			return OperationResult::failure("Could not create target directory: {$target}");
		}

		$copied  = [];
		$skipped = [];
		$failed  = [];

		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator($source, \FilesystemIterator::SKIP_DOTS),
			\RecursiveIteratorIterator::SELF_FIRST,
		);

		foreach ($iterator as $item) {
			if (!$item instanceof \SplFileInfo) {
				continue;
			}

			$relative = ltrim(str_replace($source, '', $item->getPathname()), DIRECTORY_SEPARATOR);
			$dest     = $target . DIRECTORY_SEPARATOR . $relative;

			if ($item->isDir()) {
				if (!is_dir($dest) && !mkdir($dest, 0755, true) && !is_dir($dest)) {
					$failed[] = $relative;
				}

				continue;
			}

			if (!$force && file_exists($dest)) {
				$skipped[] = $relative;

				continue;
			}

			if (!@copy($item->getPathname(), $dest)) {
				$failed[] = $relative;

				continue;
			}

			$copied[] = $relative;
		}

		if ($failed !== []) {
			return OperationResult::failure(
				'Some files could not be copied: ' . implode(', ', $failed),
				null,
				['copied' => $copied, 'skipped' => $skipped, 'failed' => $failed, 'target' => $target],
			);
		}

		// Once a Vite pipeline exists, public/assets/ holds compiled build
		// output (hashed files + manifest.json) regenerated by `npm run build`,
		// not hand-authored source — so it shouldn't be committed. Add it to
		// the project .gitignore now. (Without a build pipeline, starter static
		// assets land in the same dir and SHOULD be committed, which is why we
		// only do this here and not in the shipped skeleton .gitignore.)
		$gitignore = $this->ignoreBuildOutput();

		$summary = sprintf(
			'%d file(s) copied, %d skipped (already present)',
			count($copied),
			count($skipped),
		);
		if ($skipped !== [] && !$force) {
			$summary .= ' — re-run with --force to overwrite';
		}
		if ($gitignore === 'added') {
			$summary .= '; added /public/assets/ to .gitignore (Vite build output)';
		}

		return OperationResult::success($summary, [
			'copied'    => $copied,
			'skipped'   => $skipped,
			'target'    => $target,
			'gitignore' => $gitignore,
		]);
	}

	/**
	 * Ensure the Vite build-output directory is git-ignored at the project
	 * root. Idempotent — returns 'present' if the entry already exists,
	 * 'added' if it was appended, or 'unwritable' if the file couldn't be
	 * written. The skeleton always ships a .gitignore; if one is somehow
	 * absent it's created with just this entry.
	 *
	 * @return 'present'|'added'|'unwritable'
	 */
	private function ignoreBuildOutput(): string
	{
		$entry     = '/public/assets/';
		$gitignore = PathResolver::projectRoot() . '/.gitignore';

		$existing = is_file($gitignore) ? (string)file_get_contents($gitignore) : '';

		foreach (preg_split('/\R/', $existing) ?: [] as $line) {
			if (trim($line) === $entry) {
				return 'present';
			}
		}

		// Separate the appended block from any existing content with a blank
		// line; a fresh file starts straight at the comment.
		$block = '';
		if ($existing !== '') {
			$block .= str_ends_with($existing, "\n") ? "\n" : "\n\n";
		}
		$block .= "# Vite build output — compiled from frontend/, regenerated by `npm run build`\n";
		$block .= $entry . "\n";

		if (@file_put_contents($gitignore, $block, FILE_APPEND) === false) {
			return 'unwritable';
		}

		return 'added';
	}

	private function scaffoldDir(): string
	{
		return PathResolver::packageRoot() . '/resources/builder/frontend';
	}

	private function targetDir(): string
	{
		return PathResolver::projectRoot() . '/frontend';
	}
}
