; Inherit from system php.ini and add APCu CLI support
extension=/opt/homebrew/lib/php/pecl/20240924/apcu.so
extension=/opt/homebrew/lib/php/pecl/20240924/pcov.so

[APCu]
apc.enable_cli = 1

[pcov]
pcov.enabled = 1
pcov.directory = .