<?php

declare(strict_types=1);

namespace TotalCMS\Domain\OAuth\Adapter;

use League\OAuth2\Server\Entities\AccessTokenEntityInterface;
use League\OAuth2\Server\Entities\Traits\AccessTokenTrait;
use League\OAuth2\Server\Entities\Traits\EntityTrait;
use League\OAuth2\Server\Entities\Traits\TokenEntityTrait;

/**
 * Stateless access-token entity. Composed from league's built-in traits.
 * JWTs are generated by AccessTokenTrait::toString() at response-emit time;
 * no persistence occurs in T3's storage layer.
 */
final class LeagueAccessTokenEntity implements AccessTokenEntityInterface
{
	use AccessTokenTrait;
	use TokenEntityTrait;
	use EntityTrait;
}
