<?php

namespace TotalCMS\Domain\Security\Sanitization;

use enshrined\svgSanitize\Sanitizer;

/**
 * SVG Sanitizer for preventing XSS attacks while preserving valid SVG functionality.
 */
class SVGSanitizer
{
	private static ?Sanitizer $sanitizer = null;

	public static function sanitize(string $svg): string
	{
		if ($svg === '') {
			return '';
		}
		$sanitizer = self::getSanitizer();

		try {
			// Sanitize the SVG content
			$cleanSvg = $sanitizer->sanitize($svg);

			// Return empty string if sanitization failed
			return $cleanSvg ?: '';
		} catch (\Exception) {
			// If sanitization fails, return empty string
			return '';
		}
	}

	/**
	 * Verify that the content is valid SVG.
	 */
	public static function isValidSvg(string $svg): bool
	{
		if ($svg === '') {
			return false;
		}

		// Suppress XML errors for validation
		$prevUseErrors = libxml_use_internal_errors(true);

		try {
			$doc = new \DOMDocument();
			// Use secure XML loading options
			$doc->loadXML($svg, LIBXML_NOENT | LIBXML_NONET | LIBXML_NOBLANKS);

			// Check for XML errors
			$errors = libxml_get_errors();
			if ($errors !== []) {
				return false;
			}

			// Must contain at least one SVG element
			return $doc->getElementsByTagName('svg')->length > 0;
		} catch (\Exception) {
			return false;
		} finally {
			// Restore previous settings
			libxml_use_internal_errors($prevUseErrors);
			libxml_clear_errors();
		}
	}

	public static function sanitizeAndValidate(string $svg): string
	{
		if ($svg === '') {
			return '';
		}
		$sanitized = self::sanitize($svg);

		// Verify it's still valid SVG after sanitization
		if (!self::isValidSvg($sanitized)) {
			throw new \InvalidArgumentException('Invalid SVG content after sanitization');
		}

		$sanitized = self::removeEmptyGroups($sanitized);

		return self::uniquifyIds($sanitized);
	}

	/**
	 * Remove empty <g> elements left behind by design tools.
	 *
	 * Runs repeatedly since removing nested empty groups can reveal
	 * new empty parents.
	 */
	public static function removeEmptyGroups(string $svg): string
	{
		do {
			$svg = (string)preg_replace('/<g[^>]*>\s*<\/g>\s*/s', '', $svg, -1, $count);
		} while ($count > 0);

		return $svg;
	}

	/**
	 * Make all IDs in the SVG unique by adding a short random prefix.
	 *
	 * Design tools like Affinity Designer and Illustrator generate generic IDs
	 * (e.g. _clip1, _Linear2) that collide when multiple SVGs are on the same page.
	 * This rewrites all id definitions and their references (url(#...), href="#...",
	 * xlink:href="#...") to use unique IDs.
	 */
	public static function uniquifyIds(string $svg): string
	{
		$prefix = 'tcms-' . bin2hex(random_bytes(4)) . '-';

		// Collect all id attribute values that start with underscore (auto-generated by design tools)
		if (!preg_match_all('/\bid="(_[^"]+)"/', $svg, $matches)) {
			return $svg;
		}

		/** @var array<string> $ids */
		$ids = array_unique($matches[1]);

		// Sort longest-first to avoid partial replacements
		usort($ids, fn (string $a, string $b): int => strlen($b) - strlen($a));

		foreach ($ids as $id) {
			$newId     = $prefix . $id;
			$escapedId = preg_quote($id, '/');

			// Replace id="..." definitions
			$svg = (string)preg_replace(
				'/\bid="' . $escapedId . '"/',
				'id="' . $newId . '"',
				$svg
			);

			// Replace url(#...) references (in attributes and style properties)
			$svg = (string)preg_replace(
				'/url\(#' . $escapedId . '\)/',
				'url(#' . $newId . ')',
				$svg
			);

			// Replace href="#..." references
			$svg = (string)preg_replace(
				'/href="#' . $escapedId . '"/',
				'href="#' . $newId . '"',
				$svg
			);
		}

		return $svg;
	}

	/**
	 * Get or create SVG sanitizer instance.
	 */
	private static function getSanitizer(): Sanitizer
	{
		if (!self::$sanitizer instanceof Sanitizer) {
			self::$sanitizer = new Sanitizer();

			// Configure sanitizer for security
			self::$sanitizer->removeRemoteReferences(true);
			self::$sanitizer->minify(true); // Keep readable for debugging
			self::$sanitizer->removeXMLTag(true); // Remove XML declaration to match schema pattern
		}

		return self::$sanitizer;
	}
}
