<?php

declare(strict_types=1);

namespace TotalCMS\Domain\Mcp\Tool\Admin;

use Mcp\Exception\ToolCallException;
use Mcp\Schema\ToolAnnotations;
use TotalCMS\Domain\Object\Service\ObjectSaver;
use TotalCMS\Domain\Object\Service\ObjectUpdater;
use TotalCMS\Domain\Schema\Data\SchemaData;
use TotalCMS\Domain\Schema\Service\SchemaFetcher;
use TotalCMS\Domain\Mcp\Tool\Data\McpToolDefinition;
use TotalCMS\Domain\Mcp\Tool\Service\ToolRegistry;

/**
 * Admin tool family for collection object CRUD.
 *
 * Ships `create_object` and `update_object` as the operator's MCP-side
 * surface for writing content. The handlers are thin wrappers around the
 * same `ObjectSaver` / `ObjectUpdater` services the admin form save and
 * REST API call into, so schema validation, slug generation, event
 * dispatch (object.created / object.updated → index rebuild, cache
 * invalidation, dataview refresh), and `processBeforeSave` property
 * actions all fire for free.
 *
 * Scope for v1 — text-shaped field types only. If the target collection's
 * schema contains an image, file, gallery, or depot field at the top
 * level, the tool refuses with a clear error instead of writing
 * placeholder strings the LLM has no way to populate. Binary upload
 * needs a request-shape MCP doesn't have today (multipart bodies,
 * persistent storage handles), and pretending otherwise — the way the
 * JumpStart sync path silently regenerates fake images — produces
 * worse data than just refusing.
 *
 * Card and deck fields are allowed at the top level even though they
 * can nest binary fields, because most of the time they don't. If
 * someone submits nonsense into a nested image field, the property
 * factory's existing validation catches it.
 *
 * Delete is intentionally omitted — destructive, no undo, and the
 * existing admin UI / REST DELETE already covers it. Adding it through
 * MCP needs explicit dry-run + confirmation patterns that aren't worth
 * the cost yet.
 */
readonly class ObjectTools
{
	/**
	 * Field types whose data is binary or upload-shaped and cannot be
	 * written via a plain JSON tool call. The list mirrors the same
	 * set JumpStartExporter::processObjectData() normalizes for sync
	 * export — anything here needs an upload pipeline MCP doesn't
	 * carry, so we refuse upfront rather than corrupt the on-disk row.
	 */
	private const UNSUPPORTED_FIELD_TYPES = ['image', 'file', 'gallery', 'depot'];

	public function __construct(
		private ObjectSaver $saver,
		private ObjectUpdater $updater,
		private SchemaFetcher $schemaFetcher,
	) {
	}

	public function register(ToolRegistry $registry): void
	{
		$registry->register(new McpToolDefinition(
			name: 'create_object',
			description: 'Create a new object inside a collection. Required: collection (existing collection id) + data (field values matching the collection schema). Optional: id (otherwise derived from the schema slug/autogen rules). Errors if an object with the resolved id already exists in the collection, or if the collection schema contains an image/file/gallery/depot field — binary fields cannot be written via MCP yet.',
			access: 'admin',
			handler: $this->createHandler(...),
			inputSchema: [
				'type'                 => 'object',
				'required'             => ['collection', 'data'],
				'additionalProperties' => false,
				'properties'           => [
					'collection' => [
						'type'        => 'string',
						'description' => 'Collection id to create the object in. Discover via list_collections.',
						'examples'    => ['blog', 'team', 'reviews'],
					],
					'id' => [
						'type'        => 'string',
						'description' => 'Optional explicit id (slug-form). If omitted, the schema decides — usually slugified from the title or generated by autogen rules.',
						'examples'    => ['my-first-post', 'jane-doe'],
					],
					'data' => [
						// Plain `type: object` rather than the oneOf shape used
						// for optional `extra` fields elsewhere. `data` is
						// required and a literal `{}` payload would be
						// degenerate (ObjectSaver would reject "required schema
						// fields missing" anyway), so we let the SDK validator
						// catch that earlier rather than carrying the empty-{}
						// → PHP [] workaround that mcp/sdk needs for optional
						// fields.
						'type'        => 'object',
						'description' => 'Field values keyed by schema property name. Use describe_collection to discover the property list and their types. Binary fields (image, file, gallery, depot) are NOT supported yet — see tool description.',
					],
				],
			],
			annotations: new ToolAnnotations(
				title: 'Create Object',
				readOnlyHint: false,
				destructiveHint: false,
				idempotentHint: false,
				openWorldHint: false,
			),
		));

		$registry->register(new McpToolDefinition(
			name: 'update_object',
			description: 'Update an existing object. Required: collection + id + data. The data shape is the complete object body — fields not present in the payload revert to the schema default. Fetch the current object first via get_object if you want to patch a subset. Same binary-field restriction as create_object.',
			access: 'admin',
			handler: $this->updateHandler(...),
			inputSchema: [
				'type'                 => 'object',
				'required'             => ['collection', 'id', 'data'],
				'additionalProperties' => false,
				'properties'           => [
					'collection' => [
						'type'        => 'string',
						'description' => 'Collection id containing the object.',
						'examples'    => ['blog', 'team', 'reviews'],
					],
					'id' => [
						'type'        => 'string',
						'description' => 'Existing object id to update. Use query_collection or search_collection to discover.',
						'examples'    => ['my-first-post'],
					],
					'data' => [
						// See create_object's `data` for why plain type:object
						// rather than the oneOf empty-{} workaround.
						'type'        => 'object',
						'description' => 'Replacement field values keyed by schema property name. This is a full replace — round-trip via get_object first if you only want to change a subset.',
					],
				],
			],
			annotations: new ToolAnnotations(
				title: 'Update Object',
				readOnlyHint: false,
				destructiveHint: false,
				idempotentHint: true,
				openWorldHint: false,
			),
		));
	}

	/**
	 * @param array<string,mixed> $data
	 *
	 * @return array<string,mixed>
	 */
	public function createHandler(string $collection, array $data, ?string $id = null): array
	{
		$this->refuseIfSchemaHasBinaryFields($collection, 'create_object');

		if ($id !== null && $id !== '') {
			$data['id'] = $id;
		}

		try {
			$object = $this->saver->saveObject($collection, $data);
		} catch (\DomainException|\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'Could not create object in "%s": %s',
				$collection,
				$e->getMessage(),
			), $e->getCode(), $e);
		}

		return $object->toArray();
	}

	/**
	 * @param array<string,mixed> $data
	 *
	 * @return array<string,mixed>
	 */
	public function updateHandler(string $collection, string $id, array $data): array
	{
		$this->refuseIfSchemaHasBinaryFields($collection, 'update_object');

		// ObjectUpdater::updateObject validates that the resolved object id
		// matches the route-style $id arg. Stamp the id onto the payload
		// here so the factory builds the object with the same id and the
		// equality check passes.
		$data['id'] = $id;

		try {
			$object = $this->updater->updateObject($collection, $id, $data);
		} catch (\DomainException|\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'Could not update object "%s/%s": %s',
				$collection,
				$id,
				$e->getMessage(),
			), $e->getCode(), $e);
		}

		return $object->toArray();
	}

	/**
	 * Inspect the collection's resolved schema for any top-level field
	 * whose type is in UNSUPPORTED_FIELD_TYPES. Throws a ToolCallException
	 * naming every offending field so the agent learns what's blocking
	 * the write in one round-trip.
	 *
	 * Card and deck children aren't walked — most of the time they hold
	 * text content, and the property factory's own validation catches
	 * nonsense submitted to a nested image field at write time.
	 */
	private function refuseIfSchemaHasBinaryFields(string $collection, string $toolName): void
	{
		try {
			$schema = $this->schemaFetcher->fetchSchemaForCollection($collection);
		} catch (\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'%s: collection "%s" not found. Use list_collections to discover available collections.',
				$toolName,
				$collection,
			), $e->getCode(), $e);
		}

		$offending = $this->binaryFieldsIn($schema);
		if ($offending === []) {
			return;
		}

		throw new ToolCallException(sprintf(
			'%s: collection "%s" has binary field(s) [%s]. Image, file, gallery, and depot fields cannot be written via MCP tools yet. Edit this collection in the admin UI instead.',
			$toolName,
			$collection,
			implode(', ', array_map(
				fn (array $f): string => $f['name'] . ':' . $f['type'],
				$offending,
			)),
		));
	}

	/**
	 * @return list<array{name:string,type:string}>
	 */
	private function binaryFieldsIn(SchemaData $schema): array
	{
		$found = [];
		foreach ($schema->properties as $name => $property) {
			$field = (string)($property['field'] ?? '');
			if (in_array($field, self::UNSUPPORTED_FIELD_TYPES, true)) {
				$found[] = ['name' => (string)$name, 'type' => $field];
			}
		}

		return $found;
	}
}
