<?php

declare(strict_types=1);

namespace TotalCMS\Domain\Mcp\Tool\Admin;

use Mcp\Exception\ToolCallException;
use Mcp\Schema\ToolAnnotations;
use TotalCMS\Domain\Mcp\Tool\Data\McpToolDefinition;
use TotalCMS\Domain\Mcp\Tool\Service\ToolRegistry;
use TotalCMS\Domain\Object\Service\ObjectFetcher;
use TotalCMS\Domain\Object\Service\ObjectSaver;
use TotalCMS\Domain\Object\Service\ObjectUpdater;
use TotalCMS\Domain\Schema\Data\SchemaData;
use TotalCMS\Domain\Schema\Service\SchemaFetcher;

/**
 * Admin tool family for collection object CRUD.
 *
 * Ships `create_object` and `update_object` as the operator's MCP-side
 * surface for writing content. The handlers are thin wrappers around the
 * same `ObjectSaver` / `ObjectUpdater` services the admin form save and
 * REST API call into, so schema validation, slug generation, event
 * dispatch (object.created / object.updated → index rebuild, cache
 * invalidation, dataview refresh), and `processBeforeSave` property
 * actions all fire for free.
 *
 * Binary fields are checked at the PAYLOAD level, not the schema level: a
 * collection that merely *contains* an image / file / gallery / depot field
 * can still be written, as long as the call doesn't try to set one. Binary
 * upload needs a request-shape MCP doesn't have today (multipart bodies,
 * persistent storage handles), so a payload that puts a value into a binary
 * field is refused with a clear error naming the offenders — but omitting
 * them is fine. On create the field is left unset; on update the existing
 * object's value is preserved (updateObject is a full replace, so without
 * this a partial edit that omits the image would wipe it). This lets agents
 * build real content-rich collections (blog posts, etc.) that happen to have
 * an optional image field, instead of being blocked outright.
 *
 * Card and deck fields are allowed at the top level even though they
 * can nest binary fields, because most of the time they don't. If
 * someone submits nonsense into a nested image field, the property
 * factory's existing validation catches it.
 *
 * Delete is intentionally omitted — destructive, no undo, and the
 * existing admin UI / REST DELETE already covers it. Adding it through
 * MCP needs explicit dry-run + confirmation patterns that aren't worth
 * the cost yet.
 */
readonly class ObjectTools
{
	/**
	 * Field types whose data is binary or upload-shaped and cannot be
	 * written via a plain JSON tool call. The list mirrors the same
	 * set JumpStartExporter::processObjectData() normalizes for sync
	 * export — anything here needs an upload pipeline MCP doesn't
	 * carry, so we refuse upfront rather than corrupt the on-disk row.
	 */
	private const UNSUPPORTED_FIELD_TYPES = ['image', 'file', 'gallery', 'depot'];

	public function __construct(
		private ObjectSaver $saver,
		private ObjectUpdater $updater,
		private SchemaFetcher $schemaFetcher,
		private ObjectFetcher $objectFetcher,
	) {
	}

	public function register(ToolRegistry $registry): void
	{
		$registry->register(new McpToolDefinition(
			name: 'create_object',
			description: 'Create a new object inside a collection. Required: collection (existing collection id) + data (field values matching the collection schema). Optional: id (otherwise derived from the schema slug/autogen rules). Errors if an object with the resolved id already exists in the collection, or if the collection schema contains an image/file/gallery/depot field — binary fields cannot be written via MCP yet.',
			access: 'admin',
			handler: $this->createHandler(...),
			inputSchema: [
				'type'                 => 'object',
				'required'             => ['collection', 'data'],
				'additionalProperties' => false,
				'properties'           => [
					'collection' => [
						'type'        => 'string',
						'description' => 'Collection id to create the object in. Discover via list_collections.',
						'examples'    => ['blog', 'team', 'reviews'],
					],
					'id' => [
						'type'        => 'string',
						'description' => 'Optional explicit id (slug-form). If omitted, the schema decides — usually slugified from the title or generated by autogen rules.',
						'examples'    => ['my-first-post', 'jane-doe'],
					],
					'data' => [
						// Plain `type: object` rather than the oneOf shape used
						// for optional `extra` fields elsewhere. `data` is
						// required and a literal `{}` payload would be
						// degenerate (ObjectSaver would reject "required schema
						// fields missing" anyway), so we let the SDK validator
						// catch that earlier rather than carrying the empty-{}
						// → PHP [] workaround that mcp/sdk needs for optional
						// fields.
						'type'        => 'object',
						'description' => 'Field values keyed by schema property name. Use describe_collection to discover the property list and their types. Binary fields (image, file, gallery, depot) are NOT supported yet — see tool description.',
					],
				],
			],
			annotations: new ToolAnnotations(
				title: 'Create Object',
				readOnlyHint: false,
				destructiveHint: false,
				idempotentHint: false,
				openWorldHint: false,
			),
		));

		$registry->register(new McpToolDefinition(
			name: 'update_object',
			description: 'Update an existing object. Required: collection + id + data. The data shape is the complete object body — fields not present in the payload revert to the schema default. Fetch the current object first via get_object if you want to patch a subset. Same binary-field restriction as create_object.',
			access: 'admin',
			handler: $this->updateHandler(...),
			inputSchema: [
				'type'                 => 'object',
				'required'             => ['collection', 'id', 'data'],
				'additionalProperties' => false,
				'properties'           => [
					'collection' => [
						'type'        => 'string',
						'description' => 'Collection id containing the object.',
						'examples'    => ['blog', 'team', 'reviews'],
					],
					'id' => [
						'type'        => 'string',
						'description' => 'Existing object id to update. Use query_collection or search_collection to discover.',
						'examples'    => ['my-first-post'],
					],
					'data' => [
						// See create_object's `data` for why plain type:object
						// rather than the oneOf empty-{} workaround.
						'type'        => 'object',
						'description' => 'Replacement field values keyed by schema property name. This is a full replace — round-trip via get_object first if you only want to change a subset.',
					],
				],
			],
			annotations: new ToolAnnotations(
				title: 'Update Object',
				readOnlyHint: false,
				destructiveHint: false,
				idempotentHint: true,
				openWorldHint: false,
			),
		));
	}

	/**
	 * @param array<string,mixed> $data
	 *
	 * @return array<string,mixed>
	 */
	public function createHandler(string $collection, array $data, ?string $id = null): array
	{
		$schema = $this->fetchSchemaOrFail($collection, 'create_object');
		$binary = $this->binaryFieldsIn($schema);

		// Refuse only if the payload actually tries to write a binary field;
		// omitted binary fields are fine and left unset.
		$this->refuseIfPayloadWritesBinary($collection, 'create_object', $data, $binary);

		// Drop any empty binary keys the agent may have echoed back so they
		// don't reach the saver as stray empties.
		$data = $this->stripBinaryFields($data, $binary);

		if ($id !== null && $id !== '') {
			$data['id'] = $id;
		}

		try {
			$object = $this->saver->saveObject($collection, $data);
		} catch (\DomainException|\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'Could not create object in "%s": %s',
				$collection,
				$e->getMessage(),
			), $e->getCode(), $e);
		}

		return $object->toArray();
	}

	/**
	 * @param array<string,mixed> $data
	 *
	 * @return array<string,mixed>
	 */
	public function updateHandler(string $collection, string $id, array $data): array
	{
		$schema = $this->fetchSchemaOrFail($collection, 'update_object');
		$binary = $this->binaryFieldsIn($schema);

		$this->refuseIfPayloadWritesBinary($collection, 'update_object', $data, $binary);

		// ObjectUpdater::updateObject validates that the resolved object id
		// matches the route-style $id arg. Stamp the id onto the payload
		// here so the factory builds the object with the same id and the
		// equality check passes.
		$data['id'] = $id;

		// updateObject is a full replace — it regenerates the object from
		// $data — so any binary field omitted from the payload would be wiped.
		// Carry the existing object's binary values forward so an MCP edit
		// that omits the image keeps it.
		$data = $this->preserveBinaryFields($collection, $id, $data, $binary);

		try {
			$object = $this->updater->updateObject($collection, $id, $data);
		} catch (\DomainException|\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'Could not update object "%s/%s": %s',
				$collection,
				$id,
				$e->getMessage(),
			), $e->getCode(), $e);
		}

		return $object->toArray();
	}

	/**
	 * Resolve the collection's schema, translating the "unknown collection"
	 * exception into a ToolCallException that points the agent at
	 * list_collections.
	 */
	private function fetchSchemaOrFail(string $collection, string $toolName): SchemaData
	{
		try {
			return $this->schemaFetcher->fetchSchemaForCollection($collection);
		} catch (\UnexpectedValueException $e) {
			throw new ToolCallException(sprintf(
				'%s: collection "%s" not found. Use list_collections to discover available collections.',
				$toolName,
				$collection,
			), $e->getCode(), $e);
		}
	}

	/**
	 * Refuse the write if the payload puts a non-empty value into any binary
	 * field — those need an upload pipeline MCP doesn't have, and writing the
	 * LLM's string would corrupt the row. Names every offending field so the
	 * agent learns what to drop in one round-trip. An empty value (null / ''
	 * / []) is treated as "not writing it" and allowed through.
	 *
	 * Card and deck children aren't walked — most of the time they hold text
	 * content, and the property factory's own validation catches nonsense
	 * submitted to a nested image field at write time.
	 *
	 * @param array<string,mixed>                  $data
	 * @param list<array{name:string,type:string}> $binary
	 */
	private function refuseIfPayloadWritesBinary(string $collection, string $toolName, array $data, array $binary): void
	{
		$attempted = [];
		foreach ($binary as $field) {
			$name = $field['name'];
			if (array_key_exists($name, $data) && !$this->isEmpty($data[$name])) {
				$attempted[] = $field;
			}
		}

		if ($attempted === []) {
			return;
		}

		throw new ToolCallException(sprintf(
			'%s: collection "%s" payload sets binary field(s) [%s]. Image, file, gallery, and depot fields can\'t be written via MCP — omit them from your payload (on update they keep their current value) and edit them in the admin UI.',
			$toolName,
			$collection,
			implode(', ', array_map(
				fn (array $f): string => $f['name'] . ':' . $f['type'],
				$attempted,
			)),
		));
	}

	/**
	 * Remove every binary field key from the payload. Used on create so a
	 * stray empty echo doesn't reach the saver — binary fields are simply
	 * left unset and take their schema default.
	 *
	 * @param array<string,mixed>                  $data
	 * @param list<array{name:string,type:string}> $binary
	 *
	 * @return array<string,mixed>
	 */
	private function stripBinaryFields(array $data, array $binary): array
	{
		foreach ($binary as $field) {
			unset($data[$field['name']]);
		}

		return $data;
	}

	/**
	 * Carry the existing object's binary-field values into the update payload
	 * so the full-replace save doesn't wipe them. If the object can't be read
	 * (first write / missing), the binary keys are stripped and the updater is
	 * left to surface any not-found error.
	 *
	 * @param array<string,mixed>                  $data
	 * @param list<array{name:string,type:string}> $binary
	 *
	 * @return array<string,mixed>
	 */
	private function preserveBinaryFields(string $collection, string $id, array $data, array $binary): array
	{
		if ($binary === []) {
			return $data;
		}

		try {
			$existing = $this->objectFetcher->fetchObject($collection, $id)->toArray();
		} catch (\Throwable) {
			return $this->stripBinaryFields($data, $binary);
		}

		foreach ($binary as $field) {
			$name = $field['name'];
			if (array_key_exists($name, $existing)) {
				$data[$name] = $existing[$name];
			} else {
				unset($data[$name]);
			}
		}

		return $data;
	}

	private function isEmpty(mixed $value): bool
	{
		return in_array($value, [null, '', []], true);
	}

	/**
	 * @return list<array{name:string,type:string}>
	 */
	private function binaryFieldsIn(SchemaData $schema): array
	{
		$found = [];
		foreach ($schema->properties as $name => $property) {
			$field = (string)($property['field'] ?? '');
			if (in_array($field, self::UNSUPPORTED_FIELD_TYPES, true)) {
				$found[] = ['name' => (string)$name, 'type' => $field];
			}
		}

		return $found;
	}
}
