<?php

declare(strict_types=1);

namespace TotalCMS\Domain\Factory\Faker;

class FakerExamples
{
	public const FAKER_EXAMPLES = [
		'word',
		'words(3, false)',
		'sentence(6, true)',
		'sentences(3, false)',
		'paragraph(3, true)',
		'paragraphs(3, false)',
		'text(200)',
		'slug',
		'uuid',
		'boolean',
		'boolean(25)',
		'hexColor',
		'rgbColor',
		'safeHexColor',
		'colorName',
		'realText(200, 2)',
		'realTextBetween(160, 200, 2)',
		'imageUrl(640, 480)',
		'image(640, 480)',
		'imageBlur(640, 480)',
		'imageBW(640, 480)',
		'imageBWBlur(640, 480, 10)',
		'imageText(640, 480, \'f8f8f8\', 200)',
		'imageShapes(640, 480, \'f8f8f8\')',
		'tags(1, 5)',
		'title(\'male\')',
		'titleMale',
		'titleFemale',
		'suffix',
		'name(\'male\')',
		'firstName(\'female\')',
		'firstNameMale',
		'firstNameFemale',
		'lastName',
		'email',
		'safeEmail',
		'freeEmail',
		'companyEmail',
		'userName',
		'password(8, 16)',
		'domainName',
		'domainWord',
		'tld',
		'ipv4',
		'ipv6',
		'localIpv4',
		'macAddress',
		'userAgent',
		'iso8601',
		'date',
		'time',
		'dateTime',
		'dateTimeBetween(\'-27 week\', \'now\')',
		'dateTimeThisYear',
		'dateTimeThisMonth',
		'dayOfWeek',
		'monthName',
		'year',
		'timezone',
		'randomNumber(5)',
		'randomFloat(2, 0, 100)',
		'numberBetween(1, 100)',
		'randomDigit',
		'randomLetter',
		'numerify(\'###-###-####\')',
		'lexify(\'????-????\')',
		'bothify(\'??##-##??\')',
		'cityPrefix',
		'secondaryAddress',
		'state',
		'stateAbbr',
		'citySuffix',
		'streetSuffix',
		'buildingNumber',
		'city',
		'streetName',
		'streetAddress',
		'postcode',
		'address',
		'country',
		'countryCode',
		'languageCode',
		'currencyCode',
		'locale',
		'emoji',
		'url',
		'latitude(-90, 90)',
		'longitude(-180, 180)',
		'phoneNumber',
		'phoneNumberWithExtension',
		'tollFreePhoneNumber',
		'e164PhoneNumber',
		'catchPhrase',
		'bs',
		'company',
		'companySuffix',
		'jobTitle',
		'md5',
		'sha1',
		'sha256',
	];
}
