name: build

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ubuntu-latest
    name: PHP 8.2 Test on ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, zip, gd
          tools: composer:v2
          coverage: none

      - name: Install Yarn
        run: npm install -g yarn

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer -V

      - name: Check PHP extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer build

      - name: Run test suite
        run: composer test:build
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
